# Generated by Django 3.2.8 on 2021-10-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
