# Generated by Django 3.2.8 on 2021-10-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='p_image',
            field=models.ImageField(blank=True, upload_to='p_image'),
        ),
    ]
