# Generated by Django 3.2.8 on 2021-10-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_profileimage_p_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='p_image'),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
