# Generated by Django 3.2.8 on 2021-10-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_event_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.FileField(blank=True, upload_to='media/video'),
        ),
    ]
