# Generated by Django 3.2.8 on 2021-10-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='Users/jameschandler/projects/portfolio/Wayfarer/Nitelife/media/p_image/user.png', upload_to='media/p_image/'),
        ),
    ]
