# Generated by Django 3.2.8 on 2021-10-26 16:51

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='main_app/static/images/user.png', upload_to=main_app.models.get_image_path),
        ),
    ]
