# Generated by Django 3.2.8 on 2021-10-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
